# Generated by Django 5.2.1 on 2025-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_age_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Описание'),
        ),
    ]
